// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: proto/needleware.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_UDP Protocol = 0
	Protocol_TCP Protocol = 1
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "UDP",
		1: "TCP",
	}
	Protocol_value = map[string]int32{
		"UDP": 0,
		"TCP": 1,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_needleware_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_needleware_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{0}
}

type DecisionCode int32

const (
	DecisionCode_ACCEPT DecisionCode = 0
	DecisionCode_REJECT DecisionCode = 1
)

// Enum value maps for DecisionCode.
var (
	DecisionCode_name = map[int32]string{
		0: "ACCEPT",
		1: "REJECT",
	}
	DecisionCode_value = map[string]int32{
		"ACCEPT": 0,
		"REJECT": 1,
	}
)

func (x DecisionCode) Enum() *DecisionCode {
	p := new(DecisionCode)
	*p = x
	return p
}

func (x DecisionCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_needleware_proto_enumTypes[1].Descriptor()
}

func (DecisionCode) Type() protoreflect.EnumType {
	return &file_proto_needleware_proto_enumTypes[1]
}

func (x DecisionCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionCode.Descriptor instead.
func (DecisionCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{1}
}

type ConnectionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConnectionId) Reset() {
	*x = ConnectionId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_needleware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionId) ProtoMessage() {}

func (x *ConnectionId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needleware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionId.ProtoReflect.Descriptor instead.
func (*ConnectionId) Descriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_needleware_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needleware_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Address) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_needleware_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needleware_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type Connection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            *ConnectionId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      Protocol      `protobuf:"varint,2,opt,name=protocol,proto3,enum=me.igops.needleware.Protocol" json:"protocol,omitempty"`
	RemoteAddress *Address      `protobuf:"bytes,3,opt,name=remoteAddress,proto3" json:"remoteAddress,omitempty"`
	LocalAddress  *Address      `protobuf:"bytes,4,opt,name=localAddress,proto3" json:"localAddress,omitempty"`
	Metadata      *Metadata     `protobuf:"bytes,101,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
}

func (x *Connection) Reset() {
	*x = Connection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_needleware_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needleware_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{3}
}

func (x *Connection) GetId() *ConnectionId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Connection) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_UDP
}

func (x *Connection) GetRemoteAddress() *Address {
	if x != nil {
		return x.RemoteAddress
	}
	return nil
}

func (x *Connection) GetLocalAddress() *Address {
	if x != nil {
		return x.LocalAddress
	}
	return nil
}

func (x *Connection) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code DecisionCode `protobuf:"varint,1,opt,name=code,proto3,enum=me.igops.needleware.DecisionCode" json:"code,omitempty"`
}

func (x *Decision) Reset() {
	*x = Decision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_needleware_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needleware_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_proto_needleware_proto_rawDescGZIP(), []int{4}
}

func (x *Decision) GetCode() DecisionCode {
	if x != nil {
		return x.Code
	}
	return DecisionCode_ACCEPT
}

var File_proto_needleware_proto protoreflect.FileDescriptor

var file_proto_needleware_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f,
	0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0c, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x31, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x80, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x3b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a,
	0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd3, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65,
	0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x2e,
	0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x42, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x2e,
	0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x40, 0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0c, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65,
	0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72,
	0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4a, 0x04, 0x08, 0x05, 0x10, 0x64, 0x22, 0x41, 0x0a, 0x08,
	0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70,
	0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a,
	0x1c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x07, 0x0a, 0x03, 0x55,
	0x44, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x01, 0x2a, 0x26, 0x0a,
	0x0c, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4a,
	0x45, 0x43, 0x54, 0x10, 0x01, 0x32, 0xab, 0x01, 0x0a, 0x0a, 0x4e, 0x65, 0x65, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x12, 0x50, 0x0a, 0x0c, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x4f, 0x70,
	0x65, 0x6e, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73, 0x2e,
	0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1d, 0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70, 0x73,
	0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x21, 0x2e, 0x6d, 0x65, 0x2e, 0x69, 0x67, 0x6f, 0x70,
	0x73, 0x2e, 0x6e, 0x65, 0x65, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_needleware_proto_rawDescOnce sync.Once
	file_proto_needleware_proto_rawDescData = file_proto_needleware_proto_rawDesc
)

func file_proto_needleware_proto_rawDescGZIP() []byte {
	file_proto_needleware_proto_rawDescOnce.Do(func() {
		file_proto_needleware_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_needleware_proto_rawDescData)
	})
	return file_proto_needleware_proto_rawDescData
}

var file_proto_needleware_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_needleware_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_needleware_proto_goTypes = []interface{}{
	(Protocol)(0),         // 0: me.igops.needleware.Protocol
	(DecisionCode)(0),     // 1: me.igops.needleware.DecisionCode
	(*ConnectionId)(nil),  // 2: me.igops.needleware.ConnectionId
	(*Address)(nil),       // 3: me.igops.needleware.Address
	(*Metadata)(nil),      // 4: me.igops.needleware.Metadata
	(*Connection)(nil),    // 5: me.igops.needleware.Connection
	(*Decision)(nil),      // 6: me.igops.needleware.Decision
	nil,                   // 7: me.igops.needleware.Metadata.DataEntry
	(*emptypb.Empty)(nil), // 8: google.protobuf.Empty
}
var file_proto_needleware_proto_depIdxs = []int32{
	7, // 0: me.igops.needleware.Metadata.data:type_name -> me.igops.needleware.Metadata.DataEntry
	2, // 1: me.igops.needleware.Connection.id:type_name -> me.igops.needleware.ConnectionId
	0, // 2: me.igops.needleware.Connection.protocol:type_name -> me.igops.needleware.Protocol
	3, // 3: me.igops.needleware.Connection.remoteAddress:type_name -> me.igops.needleware.Address
	3, // 4: me.igops.needleware.Connection.localAddress:type_name -> me.igops.needleware.Address
	4, // 5: me.igops.needleware.Connection.metadata:type_name -> me.igops.needleware.Metadata
	1, // 6: me.igops.needleware.Decision.code:type_name -> me.igops.needleware.DecisionCode
	5, // 7: me.igops.needleware.Needleware.onConnOpened:input_type -> me.igops.needleware.Connection
	2, // 8: me.igops.needleware.Needleware.onConnClosed:input_type -> me.igops.needleware.ConnectionId
	6, // 9: me.igops.needleware.Needleware.onConnOpened:output_type -> me.igops.needleware.Decision
	8, // 10: me.igops.needleware.Needleware.onConnClosed:output_type -> google.protobuf.Empty
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_needleware_proto_init() }
func file_proto_needleware_proto_init() {
	if File_proto_needleware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_needleware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_needleware_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_needleware_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_needleware_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_needleware_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_needleware_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_needleware_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_needleware_proto_goTypes,
		DependencyIndexes: file_proto_needleware_proto_depIdxs,
		EnumInfos:         file_proto_needleware_proto_enumTypes,
		MessageInfos:      file_proto_needleware_proto_msgTypes,
	}.Build()
	File_proto_needleware_proto = out.File
	file_proto_needleware_proto_rawDesc = nil
	file_proto_needleware_proto_goTypes = nil
	file_proto_needleware_proto_depIdxs = nil
}
